### PR TITLE
Add TR Locales

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by HeCodes2Much** [comment]
@mikropsoft in the future can do do language though [crowdin](https://crowdin.com/project/easy-launcher) also this doesnt build.

**Comment by HeCodes2Much** [comment]
i think this should fix it but i'm not too sure

**Comment by HeCodes2Much** [comment]
@mikropsoft if you can go though this again to correct anything that would be good :)

**Comment by mikropsoft** [comment]
> @mikropsoft if you can go though this again to correct anything that would be good :)

If it is uploaded to crowdin, there is no problem, I will make other arrangements again, thanks

**Comment by HeCodes2Much** [comment]
> > @mikropsoft if you can go though this again to correct anything that would be good :)
> 
> If it is uploaded to crowdin, there is no problem, I will make other arrangements again, thanks

cheers for the update and thanks for dosing the translation if you join crowdin let me know your usename so i can set you as the proofreader

**Comment by mikropsoft** [comment]
> > > @mikropsoft if you can go though this again to correct anything that would be good :)
> > 
> > If it is uploaded to crowdin, there is no problem, I will make other arrangements again, thanks
> 
> cheers for the update and thanks for dosing the translation if you join crowdin let me know your usename so i can set you as the proofreader

Same nick

**Comment by HeCodes2Much** [comment]
> Same nick

sent you an invite

**Comment by mikropsoft** [comment]
> > Same nick
> 
> sent you an invite

I didn't see a message in the notifications, weird

**Comment by HeCodes2Much** [comment]
i have set you as a proofreader now

**Pull request merged**
